//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heros
    {
        public Heros()
        {
            this.InventaireItem = new HashSet<InventaireItem>();
        }
    
        public int Id { get; set; }
        public int CompteJoueurId { get; set; }
        public int Niveau { get; set; }
        public long Experience { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int StatStr { get; set; }
        public int StatDex { get; set; }
        public int StatInt { get; set; }
        public int StatVitalite { get; set; }
        public int MondeId { get; set; }
        public int ClasseId { get; set; }
        public string NomHero { get; set; }
        public bool EstConnecte { get; set; }
        public byte[] RowVersion { get; set; }
        public int StatVitaliteMax { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual CompteJoueur CompteJoueur { get; set; }
        public virtual Monde Monde { get; set; }
        public virtual ICollection<InventaireItem> InventaireItem { get; set; }
    }
}
