//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventaireItem
    {
        JeuEntities jeuContext = JeuEntities.CreationContext();
        public int TypeItemId { get; set; }
        public int HeroId { get; set; }
        public int Quantite { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Heros Heros { get; set; }
        public virtual TypeItem TypeItem { get; set; }
    }
}
