//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monde
    {
        public Monde()
        {
            this.Classe = new HashSet<Classe>();
            this.Heros = new HashSet<Heros>();
            this.Item = new HashSet<Item>();
            this.Monstre = new HashSet<Monstre>();
            this.ObjetMonde = new HashSet<ObjetMonde>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int LimiteX { get; set; }
        public int LimiteY { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<Classe> Classe { get; set; }
        public virtual ICollection<Heros> Heros { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Monstre> Monstre { get; set; }
        public virtual ICollection<ObjetMonde> ObjetMonde { get; set; }
    }
}
